name: Generate Diagram

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pip install diagrams
          sudo apt-get install eog

      - name: Generate diagram
        run: python generate_diagram.py
        
      - name: Upload diagram artifact
        uses: actions/upload-artifact@v2
        with:
          name: stateful_architecture_diagram
          path: ${{github.workspace}}    
